version: "3.9"
services:
  backend-api: # NestJS
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_NAME: scam_report_db

      APP_PORT: 5000
      FRONTEND_PORT: http://frontend:3000

      SECRET_KEY: PUBLIC_KEY
      FAST_API_URL: http://backend-ai:8000/api/v1

      CLOUDINARY_CLOUD_NAME: dphgide9y
      CLOUDINARY_API_KEY: 766548979252656
      CLOUDINARY_API_SECRET: aefk5acUpmB7uhv4taZXdaVjAAk

      SAFETY_API_KEY: AIzaSyBa411A_DNw6mGNQhmTNA0srOKRLiynu_o
      IPQS_API_KEY: K5PJ0z8OvGVY1gupxAesqJ2LraZix28i
      SCREENSHOT_API_KEY: AXM70RW-45H4ADS-M3RYH2W-SD53C9Q
      URLSCAN_API_KEY: 0198a45d-79e6-741a-92d5-ea46b06007a4
    depends_on:
      db:
        condition: service_healthy
      backend-ai:
        condition: service_started

  backend-ai: # FastAPI
    build:
      context: ./backend-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: scam_report_db
    depends_on:
      db:
        condition: service_healthy

  frontend: # Next.js
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend-api:5000
    depends_on:
      backend-api:
        condition: service_started
      backend-ai:
        condition: service_started

  db: # MySQL
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: scam_report_db
    ports:
      - "3307:3306" # ngoài máy sẽ connect qua 3307
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
